# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/barry/Documents/Solving-SAT-in-FPGA-UCSB/Module_Dev/Module_Dev.srcs/sources_1/bd/validation_example/ip/validation_example_processing_system7_0_1/validation_example_processing_system7_0_1.xci
# IP: The module: 'validation_example_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barry/Documents/Solving-SAT-in-FPGA-UCSB/Module_Dev/Module_Dev.gen/sources_1/bd/validation_example/ip/validation_example_processing_system7_0_1/validation_example_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'validation_example_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/barry/Documents/Solving-SAT-in-FPGA-UCSB/Module_Dev/Module_Dev.srcs/sources_1/bd/validation_example/ip/validation_example_processing_system7_0_1/validation_example_processing_system7_0_1.xci
# IP: The module: 'validation_example_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barry/Documents/Solving-SAT-in-FPGA-UCSB/Module_Dev/Module_Dev.gen/sources_1/bd/validation_example/ip/validation_example_processing_system7_0_1/validation_example_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'validation_example_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
